### ISSUE TITLE
How to use api key

### ISSUE THREAD

**Issue by Sam53534512** [LooksRare/looksrare-sdk#38]
-1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":1,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":1,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"api-rinkeby.looksrare.org:443:::::::::::::::::::::":1},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}

how to use apikey

**Comment by 0xShisui** [comment]
> how to use apikey

Set `X-Looks-Api-Key` in the request header. 

If you have any question regarding the api, I encourage you to ask on the dev discord directly.

**Comment by Sam53534512** [comment]
> > how to use apikey
> 
> Set `X-Looks-Api-Key` in the request header.
> 
> If you have any question regarding the api, I encourage you to ask on the dev discord directly.

i try

await ctx.curl(url,{
                method:'GET',
                timeout: 5000,
                contentType:'json',
                dataType: 'json',
                headers: {
                    "content-type": "application/json",
                    "X-Looks-Api-Key":"xxxxxxx"
                },

            })
but，It still doesn't work，Is that right？

**Comment by perryrare** [comment]
> > > how to use apikey
> > 
> > 
> > Set `X-Looks-Api-Key` in the request header.
> > If you have any question regarding the api, I encourage you to ask on the dev discord directly.
> 
> i try
> 
> await ctx.curl(url,{ method:'GET', timeout: 5000, contentType:'json', dataType: 'json', headers: { "content-type": "application/json", "X-Looks-Api-Key":"xxxxxxx" },
> 
> ```
>         })
> ```
> 
> but，It still doesn't work，Is that right？

We need more context on ur code example. What is `ctx`, which HTTP lib are you using etc.. Better try the full source code, so we can check ur issue on our end

**Comment by perryrare** [comment]
> > how to use apikey
> 
> Set `X-Looks-Api-Key` in the request header.
> 
> If you have any question regarding the api, I encourage you to ask on the dev discord directly.

@Sam53534512 Your question is related to API usage, and not the SDK usage. Please join our [dev discord](https://discord.gg/LooksRareDevelopers)

**Comment by Sam53534512** [comment]
> What

i use egg frame,the full source code
 const { app, ctx, logger } = this;
            let url = "https://api-rinkeby.looksrare.org/api/v1/orders/nonce?address=XXXXXXX"
             const result = await ctx.curl(url,{
                 method:'GET',
                 timeout: 5000,
                 contentType:'json',
                 dataType: 'json',
                 headers: {
                     "content-type": "application/json",
                     "X-Looks-Api-Key":"privatekey"
                 },

             }).catch((error)=>{
                 logger.info("******* error ********="+error)
             })

result:
-1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":1,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":1,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"api-rinkeby.looksrare.org:443:::::::::::::::::::::":1},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}

**Comment by hexacroes** [comment]
> > What
> 
> i use egg frame,the full source code const { app, ctx, logger } = this; let url = "https://api-rinkeby.looksrare.org/api/v1/orders/nonce?address=XXXXXXX" const result = await ctx.curl(url,{ method:'GET', timeout: 5000, contentType:'json', dataType: 'json', headers: { "content-type": "application/json", "X-Looks-Api-Key":"privatekey" },
> 
> ```
>          }).catch((error)=>{
>              logger.info("******* error ********="+error)
>          })
> ```
> 
> result: -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":1,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":1,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"api-rinkeby.looksrare.org:443:::::::::::::::::::::":1},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0) headers: {}

You do not need to specify an api-key in Rinkeby environment; if this happens on Mainnet, please join the Discord above and let us know
