### ISSUE TITLE
RPC url return error: Method eth_signTypedData is not supported

### ISSUE THREAD

**Issue by jusonalien** [LooksRare/looksrare-sdk#52]
First of all, I'm so thankful for the LooksRare dev team develop the looksrare-sdk:)

When I use the function **signMakerOrder**  in looksare-sdk to SIGN my order data, it got

```
MethodNotSupportedError: Method eth_signTypedData is not supported
```
I am sure that is the my using ethereum rpc service doesn't support the  `eth_signTypedData` method, since I check on the looksrare-sdk's [source code](https://github.com/LooksRare/looksrare-sdk/blob/master/src/sign/etherSignTypedData.ts#L43), I found we must use the Metamask like walet to reach this `sigTypedData` function.

I just wonder is there any other way to finish this signature fucntion in my local server? or other third part lib?

**Comment by 0xShisui** [comment]
Which wallet are you using ?

**Comment by jusonalien** [comment]
> Which wallet are you using ?

Idont use any wallet in my program:(

**Comment by 0xShisui** [comment]
You need a wallet to sign, the error is completely logic. No wallet -> no keys -> no signatures
