### ISSUE TITLE
Help with variables

### ISSUE THREAD

**Issue by aditya-angadi-artemis** [LooksRare/looksrare-sdk#77]
<img width="843" alt="image" src="https://user-images.githubusercontent.com/105091517/193467135-ca38cefd-8bcf-467e-94dd-53dca1413dd8.png">
Which contract should I use to get the X2Y2 Protocol fee? 

I am assuming in the above image creatorFees refer to collection royalty and protocol Fees refer to X2Y2 protocol fees

**Comment by 0xShisui** [comment]
I think you are the wrong github repo 🗺️

**Comment by 0xShisui** [comment]
If you are looking for the LR fees, it's explained here https://github.com/LooksRare/looksrare-sdk/blob/master/doc/guide.md#how-to-retrieve-the-fees
